### ISSUE TITLE
[FIX] 방 생성하기 / 생성일 이슈 & 라이팅 이슈 대응

### ISSUE THREAD

**Issue by Marchbreeze** [manito-project/manitto_android#108]
## 🚩 TO DO
- [x] 전체적인 코드 둘러보기
- [x] 생성일 타임존 이슈 대응
- [x] 미션 글씨 표시 영역 수정
- [x] 클립보드 복사 시 토스트 중복 방지
- [x] 힌트 색상 수정 & 외부 터치 시 키보드 내리기 설정
- [x] 라이팅 이슈 수정
![2024-04-02_15-16-26](https://github.com/manito-project/manitto-android/assets/97405341/eb47d95d-3452-4578-bd28-01089c149f2c)

**Comment by ethan-223** [comment]
안녕하세요:)
예전에 마니또 개발했던 김성규입니다.

제가 프로젝트를 watching 해뒀더라구요.
열심히 개발하시는 것들이 메일로 날아와서 잠시 들려봤습니다ㅎㅎ
마땅히 코멘트를 남길 경로가 없어서 열려있는 이슈에 남깁니다. 
(혹시 문제가 되면 삭제하겠습니다. 편히 말씀해주세요.)

우선, 꽤 오랫동안 멈춰있던 프로젝트인데 다시 시작해주셔서 감사합니다.
취준 때 정말 애정을 갖고 열심히 개발했던 녀석입니다.
처음으로 사용자가 꽤 늘어서 신기해했기도 하구요, 포트폴리오로도 요긴하게 잘 사용했습니다.

다만 아무래도 오래 전 코드이다보니 다시 보는게 두렵더라구요.
애정이 있었던만큼 추억이 보정되었나봅니다.
나름 코드를 잘(?)짜두었다고 생각했는데 슬쩍 보니 엉망이더군요 😂
그래서 굳이 꺼내지 않고 잘 했던 프로젝트로 묻어두고싶은 마음이 조금은 있었다는 핑계가 하나 있습니다.

사실 가장 큰 이유는, 제가 다른 프로젝트를 시작한 상태였습니다.
이 또한 운이 좋아서 사용자가 많이 늘어났고, 몇년간 꾸준히 업데이트를 해왔습니다.
그러다보니 업무와 병행하기 어려워서 산타마니또는 참여하기 힘들었네요.
PM 맡아주시는 한나님께서 산타마니또의 재기를 위해 꽤 힘써주시는데, 어중간하게 참여하는건 민폐라고 생각했습니다.

아무쪼록, 개인적인 이유들로 훌륭한 프로젝트를 방치해두었는데 이렇게 맡아주셔서 참 기쁩니다.
게다가 열정과 실력이 충분하신 분들이 와주신 것 같아서 더 반갑네요 ㅎㅎ
(레포지토리 활동 메일 폭탄으로 미루어 짐작했습니다)

잡담이 길었습니다.
오래 전 코드이고, 부족한 실력으로 이것저것 시도해본 것들이 많다보니 코드를 읽고 이해하시는게 어려우실것 같습니다.
저도 기억은 잘 안나겠지만, 혹시 히스토리 파악에 어려움이 있으시면 언제든 편하게 멘션해주세요.
괜찮으시다면 시간날때 종종 도움 드리고싶습니다 😁

그럼 앞으로 잘 부탁드리겠습니다. (_ _)

**Comment by Marchbreeze** [comment]
@ethan-223 

안녕하세요 성규님, 산타마니또 프로젝트를 새로 이어받게 된 김상호라고 합니다 :)
아직은 프로젝트 이해 단계에 있지만, 깊이 보면 볼수록 엄청난 코드들이 있더라구요 ! 특히 커스텀뷰 부분 ... ㅎㅎ
뉴비 개발자의 입장으로, 기존 코드들 열심히 분석하고 흡수하면서 승규님 배워가겠습니다 😃
기존에 만들어두신 코드에 방해가 되지 않게 ... 열심히 해나가볼게요
도움이 필요하게 된다면 꼭 연락드리겠습니다~!
연락 남겨주셔서 감사합니다 ㅎㅎ 잘 부탁드려요 😁

**Comment by haeti-dev** [comment]
@ethan-223 

안녕하세요 성규님! 산타마니또 프로젝트에 참여하게 된 이태희라고 합니다 :)
먼저, 프로젝트 기존 코드들을 맘껏 수정해도 된다고 허락해주셔서 감사합니다.
성규님이 정말 애정을 갖고 프로젝트를 하신 것이 코드에 정말 잘 느껴져서 더욱 조심히, 신중하게 개발해보도록 할게요!
아직 많이 부족하지만 많은 유저들을 포함한 이 프로젝트에 애정을 가지고 있는 모든 분들을 위해 열심히 해보도록 하겠습니다.
잘 부탁드리겠습니다!!
